apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
data:
  backup.sh: |
    #!/bin/sh

    TIMESTAMP=$(date +"%Y%m%dT%H%M%S")
    BACKUP_DIR="${BACKUP_DIR:-/backups}"
    RETENTION_DAYS="${RETENTION_DAYS:-7}"
    FILE_NAME="${PGDATABASE}-${TIMESTAMP}.sql.gz"
    FILE_PATH="${BACKUP_DIR}/${FILE_NAME}"

    mkdir -p "${BACKUP_DIR}/archive" || exit 2

    export PGPASSWORD="${PGPASSWORD}"
    pg_dump -h "${PGHOST}" -U "${PGUSER}" -d "${PGDATABASE}" -F p | gzip > "${FILE_PATH}"; 

    find "${BACKUP_DIR}" -maxdepth 1 -type f -name "${PGDATABASE}-*.sql.gz" -mtime +"${RETENTION_DAYS}" -print -exec mv {} "${BACKUP_DIR}/archive/" \; || true

